apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-resources-webhook
  labels:
    app: gitlab-resources-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-resources-webhook
  template:
    metadata:
      labels:
        app: gitlab-resources-webhook
    spec:
      serviceAccount: gitlab-resources-webhook
      containers:
        - name: gitlab-resources-webhook
          image: rochaporto/gitlab-resources-webhook:latest
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: gitlab-resources-webhook-certs
