apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gitlab-resources-webhook.gitlab.com
webhooks:
  - name: gitlab-resources-webhook.gitlab.com
    clientConfig:
      service:
        name: gitlab-resources-webhook
        namespace: gitlab
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    objectSelector:
      matchLabels:
        gitlab-runner-resources-webhook: "true"
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
