apiVersion: v1
kind: Service
metadata:
  name: gitlab-resources-webhook
  labels:
    app: gitlab-resources-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: gitlab-resources-webhook
